### ISSUE TITLE
Add ~arm to KEYWORDS in ebuilds?

### ISSUE THREAD

**Issue by sakaki-** [gordonb3/bubba-overlay#1]
Would you consider adding `~arm` to the various ebuild `KEYWORDS`? I've had to put `*/*::bubba **` in `package.accept_keywords` at the moment to use ebuilds from this overlay (e.g., in the live USB). Thx, sakaki

**Comment by gordonb3** [comment]
Good point. Did not really look at that.

Gordon

**Comment by sakaki-** [comment]
Thanks for fixing this.
