### ISSUE TITLE
SRC_URI in bubba-networkmanager ebuild still update.mybubba.org

### ISSUE THREAD

**Issue by sakaki-** [gordonb3/bubba-overlay#2]
Think it may need to be changed to update.excito.org like the other ebuilds, as update.mybubba.org seems no longer to resolve? Best, sakaki

**Comment by gordonb3** [comment]
A yes. I corrected most of them, but may have missed one or two. Currently don't have access to my development machine, but will take a look at it shortly. Must also change the license name for Code Igniter, which I misread at first and is actually MIT (so doesn't require a separate entry in the accept_license file).

**Comment by sakaki-** [comment]
Fixed now. Thanks!
